FROM centos:latest

RUN curl -sSLfo /etc/trc /etc/trc http://trivialrc.vorakl.name/trc && \
    ( cd /etc && curl -sSLf /etc/trc http://trivialrc.vorakl.name/trc.sha256 | sha256sum -c ) && \
    chmod +x /etc/trc && \
    /etc/trc --version

ENTRYPOINT ["/etc/trc"]
