FROM alpine:latest

RUN apk add --no-cache bash procps

RUN wget -qP /etc/ http://trivialrc.vorakl.name/trc && \
    ( cd /etc && wget -qO - http://trivialrc.vorakl.name/trc.sha256 | sha256sum -c ) && \
    chmod +x /etc/trc && \
    /etc/trc --version

ENTRYPOINT ["/etc/trc"]
